### ISSUE TITLE
blacklist.txt

### ISSUE THREAD

**Issue by omariobros** [hannespetur/ruvnaveidar#1]
Sæll Hannes.

Frábært tól hjá þér, en þegar það er keyrt t.d. `python3 ruvnaveidar`  ásamt  `--run` í fyrsta skiptið þá virkar allt eins og það virkar og gefur listan yfir það sem hún ætlar að echo'a í blacklist.txt

Hinsvegar þegar hún hefur sótt þættina og echo'að auðkenni þáttarins í blacklist.txt og keyrir sömu skipun aftur kemur villa á línu 172 í ruvnaveidar_utils.py sem er eftirfarandi.

```
python3 ruvnaveidar
Traceback (most recent call last):
  File "ruvnaveidar", line 29, in <module>
    api_data = fetch_programs()
  File "/media/ruv/ruvnaveidar/ruvnaveidar_utils.py", line 172, in fetch_programs
    api_data.extend(panel_data['programs'])
AttributeError: 'dict' object has no attribute 'extend'
```

Annað sem mig langar að bæta við óháð þessu og ekki vandamál sem slíkt, en það væri t.d. mjög töff og flottur fídus væri að geta raðað þáttunum í möppur bases á heiti, t.d. ef þú myndir nota -o sem væri t.d. á öðrum disk /mnt/data/tvshows/ þá myndi hann búa til möppu og season númer og þættina þar undir.

Semsagt einhvernvegin svona: python3 ruvnaveidar -o /mnt/data/tvshows/
og útkomman væri þá /mnt/data/tvshows/Radherran/S02

(Ekki krafa, bara hugmynd.)

Sá síðan að þú varst að nota Streamlink, mæli með að þú skoðir t.d. N_m3u8DL-RE

**Comment by hannespetur** [comment]
Hæ, þessi villa gerist þegar það eru sótt öll gögn um þætti/programs úr RÚV API og ætti ekki tengjast neitt hvað er í `blacklist.txt`, svo ég skil þetta ekki alveg. Gætiru sent mér allar skipanir sem þú gerðir og svo ég get reynt að framkalla sömu villu?

> Annað sem mig langar að bæta við óháð þessu og ekki vandamál sem slíkt, en það væri t.d. mjög töff og flottur fídus væri að geta raðað þáttunum í möppur bases á heiti, t.d. ef þú myndir nota -o sem væri t.d. á öðrum disk /mnt/data/tvshows/ þá myndi hann búa til möppu og season númer og þættina þar undir.

Jámm, sammála að það væri flott. Hef ekki gert þetta þar sem hjá mér læt ég FlexGet checka output möppuna sem færir þetta svo á rétta stað (plús fleira eins og að senda mér Telegram notification og laga til skráarnafnið). Þetta er úr flexget config hjá mér ef þú vilt gera eitthvað svipað:

```
variables: secrets.yml

templates:
  tv-notify:
    notify:
      entries:
        message: |+
          *{{title}}
          * has started downloading by task {{task}}
          *Episode name* {{tvmaze_episode_name|d('')}}
        via:
          - telegram:
              bot_token: '{? telegram.bot_token ?}'
              parse_mode: markdown
              recipients:
                - username: '{? telegram.username ?}'

tasks:
  # Task for moving the barnathaettir to their correct place
  move-tmp-barnathaettir:
    template: tv-notify
    filesystem:
      path: '{? path.tmp.barnathaettir ?}'
      recursive: yes
      retrieve: files
      regexp: '.*\.mp4$'
    disable:
      - seen
      - seen_info_hash
      - retry_failed
    accept_all: yes
    metainfo_series: yes
    tvmaze_lookup: yes
    move:
      to: '{? path.barnathaettir ?}/{{ tzmaze_series_name|default(series_name)|replace("/","_")|replace(":","- ")|replace(",","") }}/Season {{ series_season }}'
    content_size: { min: 1 }
```

> Sá síðan að þú varst að nota Streamlink, mæli með að þú skoðir t.d. N_m3u8DL-RE

Takk, skoða það.


Mbk. Hannes
